export const SET_CARDIO_EXERCISES = 'SET_CARDIO_EXERCISES';
export const SET_WEIGHT_EXERCISES = 'SET_WEIGHT_EXERCISES';
export const GET_EXERCISES_BY_TYPE = 'GET_EXERCISES_BY_TYPE';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const REMOVE_EXERCISE = 'REMOVE_EXERCISE';
